{% set name = "mdx_truly_sane_lists" %}
{% set version = "1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mdx_truly_sane_lists-{{ version }}.tar.gz
  sha256: b661022df7520a1e113af7c355c62216b384c867e4f59fb8ee7ad511e6e77f45

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - markdown >=2.6
    - python >=3.6

test:
  imports:
    - mdx_truly_sane_lists
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/radude/mdx_truly_sane_lists
  summary: Extension for Python-Markdown that makes lists truly sane. Custom indents for nested lists and fix for messy linebreaks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
